### ISSUE TITLE
Perf Improvement in useEmit

### ISSUE THREAD

**Issue by franleplant** [ghmendonca/socketio-hooks#1]
Hi! I was wondering if you were open to PRs to this lib. I am currently using it and love it so far, but I found a simple problem with `useEmit`. In the current implementation `useEmit` will return _always_ a new function, no matter if the arguments are different. See [src](https://github.com/ghmendonca/socketio-hooks/blob/5d7c5ef117fd15f842f329efcd97977e57a4b37f/src/hooks/useEmit.ts#L19-L21).

The use case is very simple: `I want to emit an event whenever props.person changes`. something like this

```typescript
function MyComp({person}) {
  const sendEvent = useEmit('newPerson', 'someNamespace')
  useEffect(() => {
    sendEvent()
  }, [person])
}
```

The problem is that the hooks linting will warn/err with the exhaustive dependency rule, basically complaining that we should include `sendEvent` in the dependency array.

The problem is that if we include `sendEvent` the effect callback will execute on each render because `sendEvent` is new on every render (although it is the same function semantically, it is a new function object).

Right now I am solving it like so

```typescript
function MyComp({person}) {
  const sendEvent = useEmit('newPerson', 'someNamespace')
  const sendEventRef = useRef(sendEvent)
  useEffect(() => {
    sendEvent.current()
  }, [person, sendEventRef])
}
```

And that works and stops eslint from complaining. But a proper solution
would be for `useEmit` to return the same function pointer unless its argument changes.

I think this can be achieved pretty easily by using `useCallback` like so (source for `useEmit`) (I need to test this solution but it looks like something at least very close to solving the problem):

```typescript
    return useCallback((...args: any[]) => {
        socket.emit(event, ...args);
    }, [event, namespace, socket]);
```

So, we will always return the same function pointer so long as `event`, `namespace` and `socket` are the same. We could probably omit `namespace` since `socket` derives from it.

But with this simple change we would improve this lib a lot.

If you are open for this changes I can try to squeeze out a PR.

Thanks!
Fran

**Comment by ghmendonca** [comment]
Hello! I see the problem, and you are welcome to submit a PR :)

There are couple things I want to add as well, like lazy connection, instead of connecting when provider renders, export a function to actually do the connection.

But feel free to submit the PR to fix your issue!

**Comment by franleplant** [comment]
Perfect, will try to do the change this week.

Ty
